Flash: BoronFirmware.bin
	
	particle flash --usb ./BoronFirmware.bin --force

BoronFirmware.bin: BoronFirmware.bin

	cd src
	particle make boron --saveTo ../BoronFirmware.bin --force
	cd ../

Build:
	clear
	cd src
	particle make boron --saveTo ../BoronFirmware.bin
	cd ../
	

